import csv
from xml.etree.ElementTree import Element, SubElement, Comment, tostring
import datetime
from xml.etree import ElementTree
#from ElementTree_pretty import prettify
import os
from dateutil import parser
import datetime, time
from email import utils

print("Starting to make XML file from CSV...")

generated_on = str(datetime.datetime.now())

# Configure one attribute with set()
root = Element('rss')
root.set('version', '2.0')
root.set('xmlns:itunes', 'http://www.itunes.com/dtds/podcast-1.0.dtd')

root.append(Comment('Generated by ElementTree_csv_to_xml.py for PyMOTW'))

channel = SubElement(root, 'channel')
title = SubElement(channel, 'title')
title.text = 'TAL Compiled Podcasts'
chdesc = SubElement(channel, 'description')
chdesc.text = "A compiled podcast for all TAL episodes, for personal use."
chlink = SubElement(channel, 'link')
chlink.text = "http://www.jakebathman.com/TAL"
chlang = SubElement(channel, 'language')
chlang.text = "en"
#dm = SubElement(channel, 'lastBuildDate')
#dm.text = generated_on
#dm = SubElement(channel, 'pubDate')
#dm.text = generated_on

fcsv=os.path.abspath("C:/Users/e008922/Dropbox/_Git/Python-Scripts/TAL/results/TALepisodeoutput.csv")

#print("Done Making XML shell")
with open(fcsv, 'rt') as f:
    curItem = None
    reader = csv.reader(f)
    for row in reader:
        EpisodeNum, Date, Title, Desc, Link, Notes = row
        #if 'Episode' in row:
            #next(f,None) # consume next line
            #continue # skip this line
        if EpisodeNum != 'Episode #':
            # Start a new group
            curItem = SubElement(channel, 'item')

            curDt = parser.parse(Date) 
            curDt = utils.formatdate(time.mktime(curDt.timetuple()))
            #print(curDt)
            
            curTitle=SubElement(curItem,'title')
            curTitle.text = EpisodeNum + ": " + Title
            curLink=SubElement(curItem,'link')
            curLink.text = "http://www.jakebathman.com/TAL/"
            curGuid=SubElement(curItem,'guid')
            curGuid.text = "http://www.jakebathman.com/TAL/" + EpisodeNum + ".mp3"
            curDesc=SubElement(curItem,'description')
            curDesc.text = Desc
            curPubDate=SubElement(curItem,'pubDate')
            curPubDate.text = curDt
            curEnc = SubElement(curItem, 'enclosure',
                             {'url':"http://www.jakebathman.com/TAL/" + EpisodeNum + ".mp3",
                              'length':"0",
                              'type':"audio/mpeg/",
                              })

fxml=os.path.abspath("C:/Users/e008922/Dropbox/_Git/Python-Scripts/TAL/results/TALepisodeoutput.xml")
         
output_file = open(fxml, 'w' )
output_file.write( '<?xml version="1.0" encoding="UTF-8"?>' )
output_file.write( ElementTree.tostring( root ) )
output_file.close()

print("Done making XML!")
